name: CI
on: [push, pull_request]
permissions:
  id-token: write
  contents: read
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: github-ci@sanctra.iam.gserviceaccount.com

      - uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: sanctra

      - run: gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

      - name: Build and push
        run: |
          IMAGE=us-central1-docker.pkg.dev/sanctra/sanctra-docker/sanctra-webapp:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy
        run: |
          gcloud run deploy sanctra-webapp \
            --image=us-central1-docker.pkg.dev/sanctra/sanctra-docker/sanctra-webapp:${{ github.sha }} \
            --region=us-central1 \
            --allow-unauthenticated
